---
title: 'Pinecone Test: Ascend Vs Marvel'
author: "Jason Freels"
date: "4/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

```{python}
# load libraries

import pinecone
import requests, os, zipfile
from torchvision import datasets
import random
from torchvision import transforms as ts
import torchvision.models as models

import matplotlib.pyplot as plt
from PIL import Image

from tqdm.autonotebook import tqdm
import pandas as pd

import pinecone.graph
import pinecone.service
import pinecone.connector

api_key = "54b863a2-57da-4909-a10f-0066710231c0"
pinecone.init(api_key=api_key)
```


```{python}
#define functions
class ImageEmbedder:
    def __init__(self):
        self.normalize = ts.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
        )
        # see https://pytorch.org/vision/0.8/models.html for many more model options
        self.model = models.squeezenet1_0(pretrained=True)  # squeezenet
    
    def embed(self, image_file_name):
        image = Image.open(image_file_name).convert("RGB")
        image = ts.Resize(256)(image)
        image = ts.CenterCrop(224)(image)
        tensor = ts.ToTensor()(image)
        tensor = self.normalize(tensor).reshape(1, 3, 224, 224)
        vector = self.model(tensor).cpu().detach().numpy().flatten()
        return vector


image_embedder = ImageEmbedder()


def show_images_horizontally(file_names):
    m = len(file_names)
    fig, ax = plt.subplots(1, m)
    fig.set_figwidth(1.5 * m)
    for a, f in zip(ax, file_names):
        a.imshow(Image.open(f))
        a.axis("off")
    plt.show()


def show_image(file_name):
    fig, ax = plt.subplots(1, 1)
    fig.set_figwidth(1.3)
    ax.imshow(Image.open(file_name))
    ax.axis("off")
    plt.show()

```

# manage directories (so much easier in R)

```{r}
root = rprojroot::find_root(rprojroot::is_git_root)

train_dir = file.path(root, "images","train")
test_dir = file.path(root, "images","test")
```

```{python}
df_train = pd.DataFrame()
df_test = pd.DataFrame()

train_files = os.listdir(r.train_dir)
test_files = os.listdir(r.test_dir)

train_file_names = list(map(lambda name: os.path.join(r.train_dir, name), train_files))
test_file_names = list(map(lambda name: os.path.join(r.test_dir, name), test_files))


df_train["image_file_name"] = train_file_names
df_train["embedding_id"] = [
    file_name.split(r.train_dir)[-1] for file_name in train_file_names
]
df_train["embedding"] = [
    image_embedder.embed(file_name)
    for file_name in tqdm(train_file_names)
]


df_test["image_file_name"] = test_file_names
df_test["embedding_id"] = [
    file_name.split(r.test_dir)[-1] for file_name in test_file_names
]
df_test["embedding"] = [
    image_embedder.embed(file_name)
    for file_name in tqdm(test_file_names)
]
```

```{python}
# Choosing an arbitrary name for my service
service_name = "simple-pytorch-image-search"

# Checking whether the service is already deployed.
if service_name not in pinecone.service.ls():
    graph = pinecone.graph.IndexGraph(metric="euclidean", shards=1)
    pinecone.service.deploy(service_name, graph)

conn = pinecone.connector.connect(service_name)
conn.info()

```

```{python}
acks = conn.upsert(items=zip(df_train.embedding_id, df_train.embedding)).collect()
conn.info()
```

```{python}
res = conn.query(df_test.embedding, batch_size=15).collect()  # issuing queries

```


```{python}
for i in range(0, 14):
    print(f"Query {i+1} and search results")
    show_image(df_test.image_file_name.iloc[i])
    show_images_horizontally(
        [r.train_dir + embedding_id for embedding_id in res[i].ids]
    )

    print("-" * 80)


```

